# KNEEL and Skyline inference packages share the same docker image.
FROM miptmloulu/kneel:gpu

MAINTAINER Aleksei Tiulpin, University of Oulu, Version 1.0

RUN pip install pynetdicom

RUN mkdir -p /opt/pkg-skyline/
COPY . /opt/pkg-skyline/
RUN pip install /opt/pkg-skyline/